// ---------------------------------------------------------------------
// This agent file is auto-generated by behaviac designer, but you should
// implement the methods of the agent class if necessary!
// ---------------------------------------------------------------------

using System.Collections.Generic;

namespace behaviac
{
    //[behaviac.TypeMetaInfo("FirstAgent", "")]
    [behaviac.TypeMetaInfo]
    public class FirstAgent : behaviac.Agent
    {
        // methods

        [behaviac.MethodMetaInfo]
        public void Work()
        {
            // Write your logic codes here.
        }
    }
}